spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wasted?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  profiles:
    active: google
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080
