spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wasted?useUnicode=yes&characterEncoding=UTF-8
    username: amin
    password: root
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081